name: Build and Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build \
            -t ghcr.io/abbasali-hub/ethereum-wallets:latest .

      - name: Push Docker image
        run: |
          docker push \
            ghcr.io/abbasali-hub/ethereum-wallets:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "${{ secrets.GHCR_PAT }}" | sudo docker login ghcr.io \
              -u "abbasali-hub" \
              --password-stdin

            sudo docker pull ghcr.io/abbasali-hub/ethereum-wallets:latest

            sudo docker stop ethereum-wallets || true
            sudo docker rm ethereum-wallets || true

            sudo docker run -d \
              --name ethereum-wallets \
              --restart unless-stopped \
              -p 3000:3000 \
              --env-file /home/ubuntu/eth_app/.env \
              ghcr.io/abbasali-hub/ethereum-wallets:latest
